-- This file is intentionally empty.
-- The canonical schema is in schema.sql at the project root.
-- It is mounted to PostgreSQL via docker-compose.yml:
--   ./schema.sql:/docker-entrypoint-initdb.d/schema.sql